name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [29, 30, 31] # Specify the API levels to test against
        abi: [x86, x86_64]      # Specify the ABIs (CPU architectures) to test against

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.api-level }}
        build-tools: '30.0.3'

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumented Tests on Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: google_apis
        arch: ${{ matrix.abi }}
        profile: Nexus 6
        script: ./gradlew connectedAndroidTest
